#+TITLE: Modelación Bayesiana
#+AUTHOR: Prof. Alfredo Garbuno Iñigo
#+EMAIL:  agarbuno@itam.mx
#+DATE: [Primavera, 2022]
:REVEAL_PROPERTIES:
#+LANGUAGE: es
#+OPTIONS: num:nil toc:nil timestamp:nil
#+REVEAL_REVEAL_JS_VERSION: 4
#+REVEAL_THEME: night
#+REVEAL_SLIDE_NUMBER: t
#+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Modelación Bayesiana">
#+REVEAL_INIT_OPTIONS: width:1600, height:900, margin:.2
#+REVEAL_EXTRA_CSS: ./css/mods.css
#+REVEAL_PLUGINS: (notes)
:END:
#+STARTUP: showall

* Introducción

Este es el repositorio con el contenido del curso en *Modelación Bayesiana* de la
*maestría en ciencia de datos*. También ofrecida de manera simultánea para alumnos
avanzados en las licenciaturas de matemáticas aplicadas, ciencia de datos y
actuaría.

* Objetivo

En este curso se verán temas avanzados en la visualización, simulación y
diagnóstico de modelos bayesianos para: inferencia, análisis de potencia y
calibración de procedimientos estadísticos. Se estudiará, un flujo de trabajo
bayesiano que permite validar y evaluar hipótesis. Se introducirán algunos
modelos modernos utilizados en distintas áreas como: modelos predictivos,
selección de variables y sistemas de recomendación. El material se complementará
con lecturas de artículos de divulgación e investigación a lo largo del curso.
 
* Temario

El temario para el semestre de primavera 2022 se puede encontrar [[https://github.com/ITAM-DS/modelacion-bayesiana/blob/spring-2022/docs/temario-modelacion-bayesiana.pdf][aqui]]. Este es
un plan preliminar que está sujeto al avance del curso a lo largo del semestre. 

** ¿De qué trata el curso?

En esta iteración del curso se estudiarán las bases algorítmicas de la
inferencia bayesiana (métodos de simulación por cadenas de Markov) así como los
diagnósticos pertinentes. De igual manera estudiaremos un marco de trabajo
basado en calibración y simulación para poder identificar rutas potenciales de
mejora en nuestros modelos y revisaremos principios basados en el método
científico. El curso continuará con métodos de inferencia aproximada que han
dado lugar a aplicaciones del estado de arte como sistemas de recomendación o
análisis de texto.

* Recursos

El contenido actual del curso se encuentra en la rama: [[https://github.com/ITAM-DS/modelacion-bayesiana/tree/spring-2022][spring-2022]]. La
estructura del repositorio se muestra a continuación donde tenemos a grandes
razgos:

#+begin_src bash :exports results :results org

tree -L 1 -d 

#+end_src

#+RESULTS:
| .   |             |
| ├── | css         |
| ├── | docs        |
| ├── | notas       |
| └── | rscripts    |
|     |             |
| 4   | directories |



* Horarios

El curso será los días Martes y Jueves en un horario de 13:00 a 14:30.

** Formato

El curso será remoto (vía Zoom) *por el momento*. Si las condiciones sanitarias lo
permiten el formato de la clase será ~completamente presencial~ a partir del *14 de
Febrero*. Por otro lado, salvo se indique lo contrario, ~las evaluaciones serán
presenciales~.

** Canvas

Utilizaremos este LMS para gestionar la comunicación fuera de los horarios de
clase. Asimismo, ahi tendrán acceso al calendario y las sesiones de zoom que se
necesiten a lo largo del semestre.

** Fechas importantes

#+ATTR_REVEAL: :frag (appear)
- La sesión del ~Martes 8 de Febrero~ será una sesión de ~3 horas~. El jueves 10 de Febrero *no habrá clase*.
- La sesión del ~Martes 10 de Mayo~ no habrá clases. 

** Grabaciones de clases

La clase se enriquece exponencialmente si existe una conversación entre los
asistentes. Por lo tanto, las sesiones no se grabarán (si, incluso si hay un cumpleaños!). 

* Evaluación

La evaluación del curso será por medio de:
#+ATTR_REVEAL: :frag (appear)
- Participación y tareas (30%)
- Evaluaciones parciales (30%)
- Proyecto final (40%)

La entrega de los trabajos/tareas se realizará por medio de un [[https://github.blog/2021-08-12-teaching-learning-github-classroom-visual-studio-code/][Github Classroom]]. 

* Ambiente de trabajo

El curso es agnóstico al lenguaje de programación. Sin embargo, utilizaremos [[https://mc-stan.org/][Stan]] como lenguaje para definir y ajustar modelos bayesianos (tanto asintóticamente correctos , como aproximados). En particular utilizaremos la interfase de [[https://www.r-project.org/][R]] por medio de ~cmdstanr~ pero de igual manera son bienvenidos en utilizar la interfase de [[https://www.python.org/][python]]. 

Como herramienta de trabajo tendrán que utilizar [[https://www.rstudio.com/products/rstudio/download/][Rstudio]] para poder trabajar en sus proyectos y sus tareas. En particular, el material de clase será editado en [[https://www.gnu.org/software/emacs/][GNU Emacs]] a través de =orgfiles= (archivos con sufijo ~.org~) pero pueden ser visualizados  en ~Github~.

*Nota*: Si van a utilizar ~R~ se recomienda tener instalada la versión ~4.1.1~ para tener la mejor compatibilidad con el código del curso.

** Configuración ~R~

Utilizaremos ~renv~ para mantener actualizada las herramientas de ~R~ junto con el contenido del curso. En la carpeta =notas= se encuentran los archivos de requerimientos (=renv.lock=)  con el que podrán usar los archivos que se vayan decantando en la carpeta =rscripts=. Aún asi, la configuración se irá construyendo en los ejercicios de tarea que vayamos utilizando en el curso.

** Configuración ~renv~

Se recomienda escribir en el archivo ~~/.Renviron~ la siguiente línea lo cual mantendrá el cache de ~renv~ en un lugar centralizado 

#+begin_src conf :tangle ~/.Renviron :mkdirp yes

  RENV_PATHS_ROOT=~/.renv

#+end_src

** Configuración de ~Docker~

Deseable, y próximo en anunciarse. 
