functions {
    // ... function declarations and definitions ...
}
data {
    // ... declarations ...
}
transformed data {
    // ... declarations ... statements ...
}
parameters {
    // ... declarations ...
}
transformed parameters {
    // ... declarations ... statements ...
}
model {
    // ... declarations ... statements ...
}
generated quantities {
    // ... declarations ... statements ...
}
