#+PROPERTY: header-args:R :session intro :results output

* Introducción


* Ambiente de trabajo

El curso es agnóstico al lenguaje de programación. Sin embargo, utilizaremos ~Stan~ como lenguaje para definir y ajustar modelos bayesianos (tanto asintóticamente correctos , como aproximados). En particular utilizaremos la interfase de ~R~ por medio de ~cmdstanr~ pero de igual manera son bienvenidos en utilizar la interfase de ~python~.

Como herramienta de trabajo tendrán que utilizar ~Rstudio~ para poder trabajar en sus proyectos y sus tareas. En particular, el material de clase será editado en ~emacs~ a través de =orgfiles= (archivos con sufijo ~.org~) pero pueden ser visualizados sin ningún problema en ~Github~.

*Nota*: Si van a utilizar ~R~ se recomienda tener instalada la versión ~4.1.1~ para tener la mejor compatibilidad con el código del curso.

* Configuración ~R~


#+begin_src R

  ## renv::restore()
  library(tidyverse)

#+end_src

#+RESULTS:
: ── [1mAttaching packages[22m ───────────────────────────────────────────────── tidyverse 1.3.1 ──
: [32m✔[39m [34mggplot2[39m 3.3.5     [32m✔[39m [34mpurrr  [39m 0.3.4
: [32m✔[39m [34mtibble [39m 3.1.6     [32m✔[39m [34mdplyr  [39m 1.0.7
: [32m✔[39m [34mtidyr  [39m 1.1.4     [32m✔[39m [34mstringr[39m 1.4.0
: [32m✔[39m [34mreadr  [39m 2.1.1     [32m✔[39m [34mforcats[39m 0.5.1
: ── [1mConflicts[22m ──────────────────────────────────────────────────── tidyverse_conflicts() ──
: [31m✖[39m [34mdplyr[39m::[32mfilter()[39m masks [34mstats[39m::filter()
: [31m✖[39m [34mdplyr[39m::[32mlag()[39m    masks [34mstats[39m::lag()
