
# Modelos de conteo


```{r setup, include=FALSE, message=FALSE}
library(cmdstanr)
library(rstanarm)
library(arm)
library(bayesplot)
library(loo)

library(patchwork)
library(scales)
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning=FALSE, 
                      fig.align = 'center', fig.width = 5, fig.height=3, cache = TRUE)
comma <- function(x) format(x, digits = 2, big.mark = ",")
theme_set(theme_linedraw())
color.blues <- c(NA,"#BDD7E7", "#6BAED6", "#3182BD", "#08519C", "#074789", "#063e77", "#053464")
color.itam  <- c("#00362b", "#00503f", "#006953", "#008367", "#009c7b", "#00b68f")


sin_lineas <- theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
sin_leyenda <- theme(legend.position = "none")
sin_ejes <- theme(axis.ticks = element_blank(), 
                  axis.text = element_blank())

options(mc.cores = 4)
```

```{r}
library(rethinking)
data(chimpanzees, package = "rethinking")
chimp <- chimpanzees
```

```{r}

chimp <- chimp %>% 
    mutate(actor     = factor(actor), 
           treatment = factor(1 + prosoc_left + 2 * condition), 
           labels = factor(treatment,
                         levels = 1:4,
                         labels = c("r/n", "l/n", "r/p", "l/p")))

chimp %>% 
    group_by(labels) %>% 
    tally()
```

```{r}
# renv::install("brms")
library(brms)

m.chimp.flat <- brm(data = chimp, 
          family = binomial,
          pulled_left | trials(1) ~ 1,
          prior(normal(0, 10), 
          class = Intercept),
          seed = 11,
          sample_prior = T,
          file = "fits/chimp.flat", 
          silent =  1
        )

summary(m.chimp.flat)
```

```{r}

prior_samples(m.chimp.flat) %>% 
  mutate(p = inv_logit_scaled(Intercept)) %>% 
  ggplot(aes(x = p)) +
      geom_histogram(aes(y = ..density..), binwidth = .025) +
      xlab("prior prob pull left")

```

```{r}

m.chimp.flatb <- brm(data = chimp, 
          family = binomial,
          pulled_left | trials(1) ~ 1,
          prior(normal(0, 1.5), 
          class = Intercept),
          seed = 11,
          sample_prior = T,
          file = "fits/chimp.flat.15", 
          silent =  2
        )

summary(m.chimp.flatb)
```

```{r}
bind_rows(prior_samples(m.chimp.flat), 
          prior_samples(m.chimp.flatb)) %>% 
  mutate(p = inv_logit_scaled(Intercept), 
         w = factor(rep(c(10, 1.5), each = n() / 2),
                    levels = c(10, 1.5))
         ) %>% 
  ggplot(aes(x = p, fill = w)) +
      geom_histogram(aes(y = ..density..), 
                     binwidth = .025, 
                     alpha = .5) +
      xlab("prior prob pull left") + ylim(0, 14) + sin_lineas
```



```{r}

m.chimp.flat <- stan_glm(pulled_left ~ 1, 
                           data = chimp, 
                   family = binomial('logit'), 
                   refresh = 0)

summary(m.chimp.flat, digits = 2)

```

```{r}

m.chimp.treat <- brm(data = chimp, 
          family = binomial,
          bf(pulled_left | trials(1) ~ a + b,
             a ~ 1, 
             b ~ 0 + treatment,
             nl = TRUE),
          prior = c(prior(normal(0, 1.5), nlpar = a),
                    prior(normal(0, 0.5), nlpar = b)),
          seed = 11,
          sample_prior = T,
          file = "fits/chimp.treat")

summary(m.chimp.treat)

```

```{r}
  
m.chimp.treat.ind <- brm(data = chimp, 
      family = binomial,
      bf(pulled_left | trials(1) ~ a + b,
         a ~ 1, 
         b ~ 0 + treatment,
         nl = TRUE),
      prior = c(prior(normal(0, 1.5), nlpar = a),
                prior(normal(0, 0.5), nlpar = b, coef = treatment1),
                prior(normal(0, 0.5), nlpar = b, coef = treatment2),
                prior(normal(0, 0.5), nlpar = b, coef = treatment3),
                prior(normal(0, 0.5), nlpar = b, coef = treatment4)),
      seed = 11,
      sample_prior = T,
      file = "fits/chimp.treat.ind")

summary(m.chimp.treat.ind)

```

```{r}

stan_program <- '
        data {
          int<lower=1> n;                       
          int<lower=1> n_treatment;
          int treatment[n];
          int<lower=0, upper=1> pulled_left[n];
        }
        parameters {
          real a;
          real b[n_treatment];
        }
        model {
          vector[n] p;
          for (i in 1:n) {
              p[i] = inv_logit(a + b[treatment[i]]);
          }
          pulled_left ~ binomial(1, p);
          a ~ normal(0, 1.5);
          b ~ normal(0, 0.5);
        }
'

chimp.data <- list(n = nrow(chimp),
                   n_treatment = length(levels(chimp$treatment)),
                   treatment   = chimp$treatment,
                   pulled_left = chimp$pulled_left,
                   actor       = chimp$actor)

stan_model <- write_stan_file(stan_program)

m.chimp.stan <- cmdstan_model(stan_model)

```

```{r}

chimp.muestras <- m.chimp.stan$sample(data = chimp.data, 
                          chains = 4, 
                          seed=11, 
                          refresh = 0)

chimp.muestras$cmdstan_diagnose()

chimp.muestras

```

```{r}

m.chimp.stanglm <- stan_glmer( pulled_left ~ (1 | treatment),
                               data = chimp,
                   family = binomial('logit'),
                   refresh = 0,
                   seed = 11)


summary(m.chimp.stanglm, digits = 2)
```

```{r}

m.chimp.stanglm.full <- stan_glmer(pulled_left ~  1 + (1 | actor) + (1 | treatment), 
                               data = chimp, 
                   family = binomial('logit'),
                   refresh = 0,
                   seed = 11)

summary(m.chimp.stanglm.full, digits = 2)

```

```{r}

stan_program <- '
        data {
          int<lower=1> n;                       
          int<lower=1> n_treatment;
          int<lower=1> n_actor;
          int treatment[n];
          int actor[n];
          int<lower=0, upper=1> pulled_left[n];
        }
        parameters {
          real a[n_actor];
          real b[n_treatment];
        }
        model {
          vector[n] p;
          for (i in 1:n) {
              p[i] = inv_logit(a[actor[i]] + b[treatment[i]]);
          }
          pulled_left ~ binomial(1, p);
          a ~ normal(0, 1.5);
          b ~ normal(0, 0.5);
        }
'

chimp.data <- list(n = nrow(chimp), 
                   n_treatment = length(levels(chimp$treatment)), 
                   n_actor     = length(levels(chimp$actor)), 
                   treatment   = chimp$treatment, 
                   pulled_left = chimp$pulled_left, 
                   actor       = chimp$actor)

stan_model <- write_stan_file(stan_program)

m.chimp.stan <- cmdstan_model(stan_model)

```

```{r}

chimp.muestras <- m.chimp.stan$sample(data = chimp.data, 
                          chains = 4, 
                          seed=11, 
                          refresh = 0)

chimp.muestras$cmdstan_diagnose()

chimp.muestras$cmdstan_summary()

```

```{r}

m.chimp.stanglm.prev <- stan_glm(pulled_left ~ 1 + treatment + actor , 
                           data = chimp, 
                   family = binomial('logit'), 
                   refresh = 0)

summary(m.chimp.stanglm.prev, digits = 2)
```

